<?php
/*
Template Name: Referals
Template Post Type: post, page, product
 */

get_header();
?>




<!-- <?php echo do_shortcode('[wp-referral-code var="copy_ref_link"]')?> -->
<!-- <?php echo do_shortcode('[wp-referral-code var="ref_code"]')?> -->
 <!-- <?php echo do_shortcode('[wp-referral-code var="ref_link"]')?> -->
<!-- <?php echo do_shortcode('[wp-referral-code var="invited_count"]')?> -->
<!-- <?php echo do_shortcode('[wp-referral-code var="invited_list"]')?> -->

<!-- <?php echo do_shortcode('[pie_register_form id="1" title="true" description="true" ]')?> 


 <?php 

 include 'tinkoff_pay.php';

 ?> -->





<div class="homepage_wrapper">
    <div class="homepage_content">

        <div class="homepage_block">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/group-5.png" alt="">
            <h1>Refer Your Friends & Get Cashback Earnings</h1>
            <p class="homepage_block_text_p">Take Advantage Of Our Referral Program. Refer Your Friends Or Others And Get Cashback Earnings Generated By Your Referrals. So What Are You Waiting For?</p>
            <button type="button" class="btn btn-nav-menu btn_post">GET REFER LINK</button>
        </div>

        <div class="homepage_block">
            <hr>

            <h1>How It Works?</h1>
            <p class="homepage_block_text_p">By Joining Our Referral Program, You Can Get Amazing Cashback. Have Any Doubt About How It Works? Then The Below Text Will Help You To Understand The Process.</p>




    <div class="container">
      <div class="row">
        <div class="col-xl-3 col-md-3 col-lg-3 col-sm-6 ">
            <div class="work_card">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/group4.png" class="hiw_card_img" alt="...">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/arrow-up.png" alt="..." class="arrow__1_3">
            <hr>
            <div class="card-body">
                <p class="card-text card-text_2">First, You Have To <strong>Sign Up For Our Referral Program</strong></p>
            </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-3 col-lg-3 col-sm-6 ">
            <div class="work_card">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/group11.png" class="hiw_card_img" alt="...">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/arrow-down.png" alt="..." id="arrow__22">
            <hr>
            <div class="card-body">
                <p class="card-text card-text_2">After Signing Up You Have To <strong>Generate Referral Link</strong></p>
            </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-3 col-lg-3 col-sm-6 ">
            <div class="work_card">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/group2.png" class="hiw_card_img" alt="...">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/arrow-up.png"  alt="..." class="arrow__1_3">
            <hr>
            <div class="card-body">
                <p class="card-text card-text_2">Then <strong>Share The Link</strong> With Your <strong>Friends Or Anybody You Can</strong></p>
            </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-3 col-lg-3 col-sm-6 ">
            <div class="work_card">
            <img src="<?php echo get_template_directory_uri()?>/assets/img/group33.png" class="hiw_card_img" alt="...">
            <hr>
            <div class="card-body">
                <p class="card-text card-text_2">If Purchase Our Packs Through - You Will <strong>Get A Percentage</strong></p>
            </div>
            </div>
        </div>
      </div>
            <br><br>
                <p>That Was The Referring Process. <strong>Now The Question Is How Much You'll Get Paid?</strong> Below You Will Found The Answer.</p>
    </div>

</div>
<hr>

        <div class="homepage_block">
            <h1>Get 10% Extra Commission!</h1>
            <p class="homepage_block_text_p">You'll Earn 10% Extra If One Of Your Referrers Brings A New Sale.</p>
            <img src="<?php echo get_template_directory_uri()?>/assets/img/group-15.png" alt="" id="handshake_img">
            <br>
            <button type="button" class="btn btn-nav-menu btn_post">GET REFER LINK</button>

        </div>

        <div class="homepage_block">

            <h1>How Much Do I Get Paid?</h1>
            <p class="homepage_block_text_p">Want to trade with the best? Join the Degram team now. Start winning your trades.</p>

            <div class="container">
              <div class="row">
                <div class="col-xl-4 col-md-4 col-lg-4 col-sm-12 ">
                    <div class="work_card">
                    <img src="<?php echo get_template_directory_uri()?>/assets/img/money11.png" class="hiw_card_img" alt="...">
                    <div class="card-body">
                        <p class="card-text tarif_plan"><strong>15% </strong>For 1 Month Plan</p>
                        <hr>
                        <p>You Will Get A 15% Commission On The Product Price</p>
                    </div>
                    </div>
                </div>

                <div class="col-xl-4 col-md-4 col-lg-4 col-sm-12 ">
                    <div class="work_card">
                    <img src="<?php echo get_template_directory_uri()?>/assets/img/money22.png" class="hiw_card_img" alt="...">
                    <div class="card-body">
                        <p class="card-text tarif_plan"><strong>20% </strong>For 3-12 Month Plan</p>
                    <hr>
                        <p>You Will Get 20% Commission Of The Product Price</p>
                    </div>
                    </div>
                </div>

                <div class="col-xl-4 col-md-4 col-lg-4 col-sm-12 ">
                    <div class="work_card">
                    <img src="<?php echo get_template_directory_uri()?>/assets/img/money33.png" class="hiw_card_img" alt="...">
                    <div class="card-body">
                        <p class="card-text tarif_plan"><strong>25% </strong>For Lifetime Plan</p>
                    <hr>
                        <p>You Will Get 25% Commission Of The Product Price</p>
                    </div>
                    </div>
                </div>
               </div>
            </div>



        </div>

        <div class="homepage_block">

            <h1>Get Even More Commission!</h1>
            <p class="homepage_block_text_p">Want to trade with the best? Join the Degram team now. Start winning your trades.</p>


            <div class="container">
              <div class="row">
                <div class="col-xl-6 col-md-6 col-lg-6 col-sm-12 ">
                    <div class="work_card">
                    <img src="<?php echo get_template_directory_uri()?>/assets/img/group_people1.png" class="hiw_card_img" alt="...">
                    <div class="card-body">
                        <p class="card-text sales_card">Bring <span>20</span> sales</p>
                        <hr>
                        <p>Get <strong> 25% Extra </strong> On Your Commission Bonus!</p>
                    </div>
                    </div>
                </div>

                <div class="col-xl-6 col-md-6 col-lg-6 col-sm-12 ">
                    <div class="work_card">
                    <img src="<?php echo get_template_directory_uri()?>/assets/img/group_people2.png" class="hiw_card_img" alt="...">
                    <div class="card-body">
                        <p class="card-text sales_card">Bring <span>30</span> sales</p>
                        <hr>
                        <p>Get <strong>50% Extra</strong> On Your Commission Bonus!</p>
                    </div>
                    </div>
                </div>

              </div>
            </div>

        </div>

        <div class="homepage_block">
            <h1>Got Questions Before Getting Started?</h1>
            <p class="homepage_block_text_p">If you have any questions about any of this, please let us know and we'll be with you as soon as we can!</p>
            <button type="button" class="btn btn-nav-menu btn_post">ASK AWAY, WE’RE HERE TO HELP</button>
        </div>






    </div>

<?php
get_footer();
